<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_mynewsdesk"
 *
 * Auto generated by Extension Builder 2013-04-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'MyNewsDesk import',
    'description' => 'Import of MyNewsDesk news items into TYPO3 news extension',
    'category' => 'be',
    'author' => 'Pixelant',
    'author_email' => 'info@pixelant.net',
    'author_company' => 'Pixelant',
    'state' => 'stable',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
