<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_mynewsdesk"
 *
 * Auto generated by Extension Builder 2013-04-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Mynewsdesk import',
	'description' => 'Import of Mynewsdesk news items into TYPO3 table
',
	'category' => 'plugin',
	'author' => 'Maksym Leskiv',
	'author_email' => 'maksym@pixelant.se',
	'author_company' => 'Pixelant AB',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.5-6.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>